require 'nokogiri'
require 'awesome_print'
require 'securerandom'
require 'json'
require 'namae'


docs = []

images_extensions = ['jpeg', 'png']

# wrap a child with a div
def wrap_image(img, doc)
  # create a node <div>
  wrapper = Nokogiri::XML::Node.new('span', doc)
  wrapper[:class] = img[:class] == 'inline' ?  'img-wrapper img-wrapper-inline' : 'img-wrapper';

  # wrap img with the wrapper div
  img.wrap(wrapper.to_html)
end

# wrap a child with a div
def wrap_chapter(chapter, doc, index)
  # create a node <div>
  wrapper = Nokogiri::XML::Node.new('div', doc)
  wrapper[:class] = "chapter-#{index}";

  # wrap img with the wrapper div
  chapter.wrap(wrapper.to_html);
end




for i in 0..11
  doc = File.open("./source/document#{i}.html") { |f| Nokogiri::HTML(f) }

  doc.search('p').each do |s|
    uniq = SecureRandom.hex(3)
    s[:id] = uniq
  end


  doc.search('img').each do |img|
    file_extension = img[:src].split('.').last

    if images_extensions.include? file_extension
      img[:src] = img[:src]
      
      replace = "#{i}"
      if i < 10
      replace = "0" + replace
      end

      img[:src] = img[:src].gsub("media/", "((REPLACE_WITH_MEDIA_ENDPOINT))/chapter-#{replace}-").gsub('.png', '.jpg').gsub('.jpeg', '.jpg')

      # remove styles
      img.delete('style');

      # wrap image with a wrapper div
      wrap_image(img, doc)
    else
      # remove not valid img nodes
      img.remove
    end
  end


  doc.search('div').each do |div|
    if div[:class] == 'stdfooter autogenerated'
      div.remove
    end
  end

  # generate a tagged file for each chapter
  File.write("./output/output-tagged-#{i}.html", doc.to_html);

  docs << doc.at('body').inner_html
end

header = '<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
   <head>
      <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
   </head>
   <body>'

footer = '</body></html>'

body = [];

docs.each_with_index do |chapter, index|

  ap index

  body << '<div class="chapter-' + index.to_s + '">' + chapter + '</div>';

end

# generate a unique file for full-text targeting
File.write("./output/output-tagged-full-text.html", header + body.join('') + footer)